# configs/params.yaml
# Configuration file for genovo_traderv2 - Increased seq_length

# --- General Settings ---
mode: 'simulation' # Start with 'simulation' or 'train' first, then switch to 'live' for demo trading
symbols:
  - 'EURUSDm' # Updated Symbol Format
  - 'GBPUSDm' # Updated Symbol Format
  - 'USDJPYm' # Updated Symbol Format
  - 'AUDUSDm' # Updated Symbol Format
  - 'USDCADm' # Updated Symbol Format
  # Add other symbols using the correct '...m' format if needed
results_dir: 'results/'

# --- MT5 Connection Configuration (mt5_config) ---
# !! CONFIGURED FOR DEMO ACCOUNT !!
mt5_config:
  # !! Exness MT5 *DEMO* details !!
  login: 209571100             # Your Exness MT5 *DEMO* account number
  password: "Abioye@16"        # Your Exness MT5 *DEMO* account password
  server: "Exness-MT5Trial9"   # Your Exness *DEMO* server
  # !! Correct path to MT5 terminal executable on Windows !!
  path: "C:/Program Files/MetaTrader 5/terminal64.exe"
  default_slippage: 3
  retry_attempts: 3
  retry_delay_sec: 0.5
  magic_number: 23456 # Example magic number

# --- API Keys (api_keys) ---
# Store external API keys here (currently unused by code)
api_keys:
  fred_api_key: "e225fb27a4fcba9f278f7623e30fbb46"
  newsapi_key: "ad32ddeb84e14ac89bb7dd13f87e0693"

# --- Notification Settings (notifications) ---
# For sending email alerts
notifications:
  email_enabled: true # Email notifications are enabled
  email_address: "tafolabi009@gmail.com"
  email_password: "jhbv znwi xxop yzyl" # Use App Password for Gmail if 2FA is enabled
  email_smtp_server: "smtp.gmail.com"
  email_smtp_port: 587
  email_recipient: "tabioye009@gmail.com,tafolabi009@gmail.com,ifeoluwaadegbite15@gmail.com" # Comma-separated list

# --- Data Configuration (data_config) ---
data_config:
  source: 'mt5'
  timeframe: 'M1'
  num_bars: 100000 # Keep reduced number of bars for now

# --- Feature Engineering Configuration (feature_config) ---
feature_config:
  window_sizes: [5, 10, 20, 50, 100, 200] # Max window is 200
  # num_features should ideally be determined dynamically after feature extraction
  # but keep it here if the model architecture requires a fixed input size beforehand.
  # Ensure this matches the actual number of features generated by features.py
  # num_features: 50 # Example: This might need adjustment based on actual features

# --- Model Configuration (model_config) ---
model_config:
  load_path_base: 'results/'
  save_path_base: 'results/'
  # num_features should match the output of the feature pipeline
  # num_features: 50 # Example: Adjust if needed
  seq_length: 201 # Increased sequence length > max window size (200)
  hidden_size: 128
  num_layers: 2
  tcn_channels: [64, 128, 128]
  tcn_kernel_size: 3
  num_heads: 4
  num_transformer_layers: 2
  dropout: 0.2

# --- Strategy Configuration (strategy_config) ---
strategy_config:
  agent_config: # PPO Agent hyperparameters
    learning_rate: 0.0001
    gamma: 0.99
    lambda_gae: 0.95
    ppo_epsilon: 0.2
    ppo_epochs: 8
    batch_size: 64
    entropy_coef: 0.01
    value_loss_coef: 0.5
    catastrophic_memory_size: 20

  reward_config: # Parameters for the custom reward function
    pnl_scale: 100.0
    profit_bonus_factor: 1.1
    loss_penalty_factor: 1.5
    max_loss_penalty: -50.0
    uncertainty_penalty_factor: 0.5
    high_volatility_penalty_factor: 0.3
    trend_follow_bonus: 0.1
    mean_revert_bonus: 0.1
    trend_against_penalty: -0.2
    mean_revert_against_penalty: -0.2
    uncertain_regime_penalty: -0.1
    holding_penalty_factor: -0.001
    profit_capture_bonus: 0.5
    quick_profit_bonus_factor: 0.2
    sharpe_ratio_bonus_factor: 0.05
    catastrophic_threshold: -20.0
    catastrophic_repeat_penalty: -10.0
    transaction_cost_penalty: -0.01

# --- Portfolio Capital Management Configuration (portfolio_capital_config) ---
portfolio_capital_config:
  initial_capital: 10000.0 # Start demo simulation with typical demo balance
  max_total_risk_pct: 0.05
  max_allocation_per_trade_pct: 0.02
  allocation_method: 'confidence_weighted'
  kelly_fraction: 0.5
  min_position_notional: 100

# --- Simulator Configuration (simulator_config) ---
simulator_config:
  commission_pct: 0.00005 # Example: 0.005% per side (adjust based on broker)
  slippage_pct: 0.0001   # Example: 0.01% slippage (adjust based on testing/reality)
  update_agent_every: 256
  print_every: 500
  plot_results: true

# --- Live Trading Configuration (live_config) ---
# Used when mode = 'live' (will run on demo account)
live_config:
  loop_interval_sec: 5
  delay_after_close_ms: 500 # Delay in milliseconds after closing a position before opening another

# --- Logging Configuration (logging_config) ---
logging_config:
  log_level: 'INFO' # Set to 'DEBUG' for more detailed logs
  log_file: 'results/genovo_traderv2_demo.log'

