# configs/params.yaml
# Configuration file for genovo_traderv2 - Configured for Training Simulation

# --- General Settings ---
mode: 'simulation' # Set to 'simulation' for training runs
symbols:
  - 'EURUSDm'
  - 'GBPUSDm'
  - 'USDJPYm'
  - 'AUDUSDm'
  - 'USDCADm'
results_dir: 'results/'

# --- MT5 Connection Configuration (mt5_config) ---
# Used for fetching historical data during training
mt5_config:
  login: 209571100
  password: "Abioye@16" # Consider using environment variables or secrets management for credentials
  server: "Exness-MT5Trial9"
  path: "C:/Program Files/MetaTrader 5/terminal64.exe"
  default_slippage: 3
  retry_attempts: 3
  retry_delay_sec: 0.5
  magic_number: 23456

# --- API Keys (api_keys) ---
# Not directly used in core training loop based on provided code, but kept for completeness
api_keys:
  fred_api_key: "e225fb27a4fcba9f278f7623e30fbb46"
  newsapi_key: "ad32ddeb84e14ac89bb7dd13f87e0693"

# --- Notification Settings (notifications) ---
# Used for sending updates/errors during training/live runs
notifications:
  email_enabled: true
  email_address: "tafolabi009@gmail.com"
  email_password: "jhbv znwi xxop yzyl" # Consider using environment variables or app passwords
  email_smtp_server: "smtp.gmail.com"
  email_smtp_port: 587
  email_recipient: "tabioye009@gmail.com,tafolabi009@gmail.com,ifeoluwaadegbite15@gmail.com"

# --- Data Configuration (data_config) ---
data_config:
  source: 'mt5'
  timeframe: 'M1'
  num_bars: 50000 # Number of historical bars to load for training

# --- Feature Engineering Configuration (feature_config) ---
feature_config:
  window_sizes: [5, 10, 20, 50, 100, 200]
  donchian_lower: 240 # ~4 hours M1
  donchian_upper: 480 # ~8 hours M1

# --- Model Configuration (model_config) ---
model_config:
  load_path_base: 'results/' # Where to load existing models from (if resuming)
  save_path_base: 'results/' # Where to save trained models
  num_features: 116 # *** CORRECTED based on features.py calculation ***
  seq_length: 201 # Input sequence length for the model
  hidden_size: 128
  num_layers: 2
  tcn_channels: [64, 128, 128]
  tcn_kernel_size: 3
  num_heads: 4
  num_transformer_layers: 2
  dropout: 0.2

# --- Strategy Configuration (strategy_config) ---
strategy_config:
  agent_config: # PPO Agent hyperparameters
    learning_rate: 0.0001
    gamma: 0.99 # Discount factor for future rewards
    lambda_gae: 0.95 # Generalized Advantage Estimation lambda
    ppo_epsilon: 0.2 # PPO clipping parameter
    ppo_epochs: 8 # Number of optimization epochs per PPO update
    batch_size: 64
    entropy_coef: 0.02 # Exploration bonus coefficient
    value_loss_coef: 0.5 # Coefficient for the value function loss
    catastrophic_memory_size: 20 # Memory for repeated bad trades

  # --- Simplified Reward Config for Initial Training ---
  reward_config:
    pnl_scale: 100.0             # Scales the profit/loss component of the reward
    profit_bonus_factor: 1.5     # Bonus multiplier for realized profits
    loss_penalty_factor: 1.5     # Penalty multiplier for realized losses
    max_loss_penalty: -10.0      # Maximum penalty for hitting stop loss
    holding_penalty_factor: 0.0  # *** CHANGED: Removed penalty for holding to encourage initial trades ***
    profit_capture_bonus: 1.0    # Bonus for closing a profitable trade via action (not TP)
    transaction_cost_penalty: -0.05 # Small penalty per transaction cost incurred
    # --- Other complex penalties/bonuses are OFF for simplification ---
    uncertainty_penalty_factor: 0.0
    high_volatility_penalty_factor: 0.0
    trend_follow_bonus: 0.0
    mean_revert_bonus: 0.0
    trend_against_penalty: 0.0
    mean_revert_against_penalty: 0.0
    uncertain_regime_penalty: 0.0
    quick_profit_bonus_factor: 0.0
    sharpe_ratio_bonus_factor: 0.0
    catastrophic_threshold: -20.0 # PnL threshold considered catastrophic
    catastrophic_repeat_penalty: -5.0 # Penalty for repeated catastrophic losses

# --- Portfolio Capital Management Configuration (portfolio_capital_config) ---
portfolio_capital_config:
  initial_capital: 5000.0 # *** CHANGED: Increased for simulation to allow trades ***
  max_total_risk_pct: 0.05 # Max % of total capital at risk across all open positions
  max_allocation_per_trade_pct: 0.02 # Max % of capital to risk on a single new trade
  allocation_method: 'confidence_weighted' # How to distribute risk among signals
  kelly_fraction: 0.5 # Parameter for Kelly criterion if used (not default here)
  min_position_notional: 100 # Minimum required notional value for a trade (in account currency)

# --- Simulator Configuration (simulator_config) ---
simulator_config:
  commission_pct: 0.00005 # Broker commission per trade value
  slippage_pct: 0.0001 # Simulated slippage per trade value
  update_agent_every: 256 # How many simulation steps between PPO updates
  print_every: 500 # How often to print simulation status
  plot_results: true # Whether to generate a plot at the end of simulation

# --- Live Trading Configuration (live_config) ---
# Not used when mode='simulation', but kept for completeness
live_config:
  loop_interval_sec: 5
  delay_after_close_ms: 500

# --- Logging Configuration (logging_config) ---
logging_config:
  log_level: 'INFO' # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  log_file: 'results/genovo_traderv2_demo.log' # Path to the log file

